open-ai:
  model: gpt-3.5-turbo
  scheme: https://api.openai.com
  key: ${OPENAI_KEY}

redis:
  host: ${REDIS_HOST}
  port: ${REDIS_PORT}
  password: ${REDIS_PASSWORD}
  topic: evaluation_queue
  interval: 1

jwt:
  key: ${JWT_KEY}
  access-token-expiration: 1800000
  refresh-token-expiration: 900000

frontend:
  host: ${REACT_HOST}
  port: ${REACT_PORT}


## H2 Configuration
spring:
  datasource:
    url: jdbc:h2:mem:user-db;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE;
    username: admin
    password: password
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
        use_sql_comments: true
        format_sql: true
    defer-datasource-initialization: true