open-ai:
  model: gpt-3.5-turbo
  scheme: https://api.openai.com
  key: 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

redis:
  host: 127.0.0.1
  port: 6379
  topic: evaluation_queue
  interval: 1000